### ISSUE TITLE
self-destruct opcode pattern incorrect

### ISSUE THREAD

**Issue by macfarla** [Consensys/besu-sequencer-plugins#126]
```
     stackSettings:
-      pattern: TWO_ZERO
+      pattern: ONE_ZERO
       alpha: 0
       delta: 1
       nbAdded: 0
       nbRemoved: 1
```
