### ISSUE TITLE
feat: Enable `go-corset` in Github Actions

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#908]
The goal here is to actually enable `go-corset` to be used in the CI pipeline.  At this time, there remains an outstanding resource usage limitation which is preventing it being enabled.  Once this is resolved, we can use a supplementary action this initially:

```
   go-corset-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CONSTRAINTS_SSH_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Install Go
        uses: actions/setup-go@v4

      - name: Install Go Corset
        run:
          go install github.com/consensys/go-corset/cmd/go-corset@latest

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Rust Corset
        run: RUSTFLAGS=-Awarnings cargo install --git ssh://git@github.com/ConsenSys/corset --tag v9.7.13 --locked --force

      - name: Run unit tests
        run: ./gradlew -i :arithmetization:test
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand
```
